# Appveyor CI configuration for vcpkg project.
#
# Copyright 2018 Hiroshi Miura
#
image: Visual Studio 2017
shallow_clone: false

environment:
  matrix:
    - VCPKG_DEFAULT_TRIPLET: x86-windows
    - VCPKG_DEFAULT_TRIPLET: x86-windows-static
    - VCPKG_DEFAULT_TRIPLET: x64-windows
    - VCPKG_DEFAULT_TRIPLET: x64-windows-static
    - VCPKG_DEFAULT_TRIPLET: arm-uwp

install:
  - ps: |
      ./scripts/bootstrap.ps1
      # Detect modified ports and make changes list
      # fetch upstream project which is necessary for forked project to compare with.
      git remote add upstream https://github.com/Microsoft/vcpkg.git
      git fetch -q upstream
      $targets = git diff --name-only upstream/master... |
          ?{$_ -match "ports/(?<change>.*?)/"} | %{$Matches.change} | Group-Object | % Name
      if([string]::IsNullOrWhitespace($targets)) { $targets = "zlib" }
      ./vcpkg.exe remove  $targets --recurse
      ./vcpkg.exe install $targets --recurse --keep-going
      ./vcpkg.exe export $targets --zip

build: off
test: off
deploy: off

artifacts:
  - path: '*.zip'
