# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- fix-libiconv-targets

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: ls
  displayName: List files

steps:
- script: ./bootstrap-vcpkg.sh
  displayName: 'Bootstrap vcpkg'

- script: ./vcpkg install collada-dom
  displayName: 'Install collada-dom'
