# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: MIT
#

jobs:
- job: x64_linux
  pool:
    name: ${{ parameters.poolName }}

  timeoutInMinutes: 1440 # 1 day

  steps:
  - bash: |
      df -h
    displayName: 'Report on Disk Space Before Environment'
  - task: Bash@3
    displayName: 'Initialize Environment'
    inputs:
      filePath: scripts/azure-pipelines/linux/initialize-environment.sh
  - bash: |
      df -h
    displayName: 'Report on Disk Space After Environment'
  - task: Bash@3
    displayName: 'Build vcpkg'
    inputs:
      filePath: bootstrap-vcpkg.sh
  - powershell: |
      $skipList = ./scripts/azure-pipelines/generate-skip-list.ps1 -Triplet "x64-linux" -BaselineFile "$(System.DefaultWorkingDirectory)/scripts/ci.baseline.txt"
      mkdir $(System.ArtifactsDirectory)/xml-results
      mkdir /ci/home
      $env:HOME = '/ci/home'
      ./vcpkg ci x64-linux --x-xunit="$(System.ArtifactsDirectory)/xml-results/x64-linux.xml" --exclude=$skipList --binarycaching
    displayName: '** Test Modified Ports **'
  - task: PowerShell@2
    displayName: 'Analyze results and prepare test logs'
    inputs:
      failOnStderr: true
      filePath: 'scripts/azure-pipelines/analyze-test-results.ps1'
      arguments: '-baselineFile $(System.DefaultWorkingDirectory)/scripts/ci.baseline.txt -logDir "$(System.ArtifactsDirectory)/xml-results" -outputDir "$(Build.ArtifactStagingDirectory)" -failurelogDir "archives/fail" -triplets "x64-linux" -errorOnRegression'
  - bash: |
      df -h
    displayName: 'Report on Disk Space After Build'
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: x86-linux Build Failure Logs'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/failureLogs'
      ArtifactName: 'x64-linux port build failure logs'
    condition: failed()
