# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: MIT
#

jobs:
- job: x64_linux
  pool:
    name: ${{ parameters.poolName }}
  workspace:
    clean: resources
  timeoutInMinutes: 1440 # 1 day
  steps:
  - bash: |
      df -h
    displayName: 'Report on Disk Space Before Environment'
    condition: always()
  - task: Bash@3
    displayName: 'Initialize Environment'
    inputs:
      filePath: scripts/azure-pipelines/linux/initialize-environment.sh
  - bash: |
      sudo mkdir /home/agent -m=777
      sudo chown `id -u` /home/agent
      exit 0
    displayName: 'Create /home/agent'
  - bash: |
      df -h
    displayName: 'Report on Disk Space After Environment'
    condition: always()
  - task: Bash@3
    displayName: 'Build vcpkg'
    inputs:
      filePath: bootstrap-vcpkg.sh
      arguments: "-buildTests"
  - bash: toolsrc/build.rel/vcpkg-test
    displayName: 'Run vcpkg tests'
  - powershell: |
      ./vcpkg x-ci-clean
      $skipList = ./scripts/azure-pipelines/generate-skip-list.ps1 -Triplet "x64-linux" -BaselineFile "$(System.DefaultWorkingDirectory)/scripts/ci.baseline.txt"
      mkdir $(System.ArtifactsDirectory)/xml-results
      $env:HOME = '/home/agent'
      ./vcpkg ci x64-linux --x-xunit="$(System.ArtifactsDirectory)/xml-results/x64-linux.xml" --exclude=$skipList --binarycaching
    displayName: '** Test Modified Ports **'
  - task: PowerShell@2
    displayName: 'Analyze results and prepare test logs'
    inputs:
      failOnStderr: true
      filePath: 'scripts/azure-pipelines/analyze-test-results.ps1'
      arguments: '-baselineFile $(System.DefaultWorkingDirectory)/scripts/ci.baseline.txt -logDir "$(System.ArtifactsDirectory)/xml-results" -outputDir "$(Build.ArtifactStagingDirectory)" -failurelogDir "archives/fail" -triplets "x64-linux" -errorOnRegression'
  - bash: |
      df -h
    displayName: 'Report on Disk Space After Build'
    condition: always()
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: x86-linux Build Failure Logs'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/failureLogs'
      ArtifactName: 'x64-linux port build failure logs'
    condition: failed()
