# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: MIT
#
variables:
  windows-pool: 'PrWin-2021-09-08'
  linux-pool: 'PrLin-2021-09-08'
  osx-pool: 'PrOsx-2021-07-27'

jobs:
- template: windows/azure-pipelines.yml
  parameters:
    triplet: x86-windows
    jobName: x86_windows
    poolName: $(windows-pool)

- template: windows/azure-pipelines.yml
  parameters:
    triplet: x64-windows
    jobName: x64_windows
    poolName: $(windows-pool)

- template: windows/azure-pipelines.yml
  parameters:
    triplet: x64-windows-static
    jobName: x64_windows_static
    poolName: $(windows-pool)

- template: windows/azure-pipelines.yml
  parameters:
    triplet: x64-windows-static-md
    jobName: x64_windows_static_md
    poolName: $(windows-pool)

- template: windows/azure-pipelines.yml
  parameters:
    triplet: x64-uwp
    jobName: x64_uwp
    poolName: $(windows-pool)

- template: windows/azure-pipelines.yml
  parameters:
    triplet: arm64-windows
    jobName: arm64_windows
    poolName: $(windows-pool)

- template: windows/azure-pipelines.yml
  parameters:
    triplet: arm-uwp
    jobName: arm_uwp
    poolName: $(windows-pool)

- template: osx/azure-pipelines.yml
  parameters:
    poolName: $(osx-pool)
    ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
      mode: AllPorts
    ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
      mode: NonTensorflow
- ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
  - template: osx/azure-pipelines.yml
    parameters:
      poolName: $(osx-pool)
      mode: OnlyTensorflow
      jobName: x64_osx_tensorflow

- template: linux/azure-pipelines.yml
  parameters:
    poolName: $(linux-pool)
