# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: MIT
#
variables:
  windows-pool: 'PrWin-2021-07-14'
  linux-pool: 'PrLin-2021-07-14'
  osx-pool: 'PrOsx-2021-04-16'

stages:
- stage: FormatChecks
  displayName: 'Formatting and Documentation Checks'
  pool: $(windows-pool)
  jobs:
  - job:
    workspace:
      clean: resources
    variables:
    - name: VCPKG_DOWNLOADS
      value: D:\downloads
    - name: DiffFile
      value: $(Build.ArtifactStagingDirectory)\format.diff
    steps:
    - task: Powershell@2
      displayName: 'Generate Documentation'
      inputs:
        filePath: 'docs/regenerate.ps1'
        arguments: '-VcpkgRoot . -WarningAction Stop'
        pwsh: true
    - script: .\bootstrap-vcpkg.bat
      displayName: 'Bootstrap vcpkg'
    - script: '.\vcpkg.exe format-manifest --all'
      displayName: 'Format Manifests'
    - task: Powershell@2
      displayName: 'Create Diff'
      inputs:
        filePath: scripts/azure-pipelines/Create-PRDiff.ps1
        arguments: '-DiffFile $(DiffFile)'
        pwsh: true
    - task: PublishBuildArtifacts@1
      condition: failed()
      displayName: 'Publish Format and Documentation Diff'
      inputs:
        PathtoPublish: '$(DiffFile)'
        ArtifactName: 'format.diff'
- stage: RunPrTests
  displayName: 'Run PR Tests:'
  dependsOn: FormatChecks
  jobs:
  - template: windows/azure-pipelines.yml
    parameters:
      triplet: x86-windows
      jobName: x86_windows
      poolName: $(windows-pool)

  - template: windows/azure-pipelines.yml
    parameters:
      triplet: x64-windows
      jobName: x64_windows
      poolName: $(windows-pool)

  - template: windows/azure-pipelines.yml
    parameters:
      triplet: x64-windows-static
      jobName: x64_windows_static
      poolName: $(windows-pool)

  - template: windows/azure-pipelines.yml
    parameters:
      triplet: x64-windows-static-md
      jobName: x64_windows_static_md
      poolName: $(windows-pool)

  - template: windows/azure-pipelines.yml
    parameters:
      triplet: x64-uwp
      jobName: x64_uwp
      poolName: $(windows-pool)

  - template: windows/azure-pipelines.yml
    parameters:
      triplet: arm64-windows
      jobName: arm64_windows
      poolName: $(windows-pool)

  - template: windows/azure-pipelines.yml
    parameters:
      triplet: arm-uwp
      jobName: arm_uwp
      poolName: $(windows-pool)

  - template: osx/azure-pipelines.yml
    parameters:
      poolName: $(osx-pool)

  - template: linux/azure-pipelines.yml
    parameters:
      poolName: $(linux-pool)
