name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v6
        with:
          stale-issue-message: 'We hope the question was answered satisfactorily. This issue will be automatically closed in 7 days if there is no response.'
          only-labels: 'category:question'
          days-before-issue-stale: 10
          days-before-pr-stale: -1
      - uses: actions/stale@v6
        with:
          stale-issue-message: 'We could not reproduce this error. Does the problem still exists? This issue will be automatically closed in 7 days if there is no response.'
          only-labels: 'requires:repro'
          days-before-issue-stale: 60
          days-before-pr-stale: -1
      - uses: actions/stale@v6
        with:
          close-issue-message: "If you wish to add this port in the future, you can reopen this issue, but we're closing it for now."
          ony-of-labels: 'category:new-port'
          close-issue-label: 'new-port-unresolved'
          days-before-issue-stale: 60
          days-before-pr-stale: -1
